# -*- coding: utf-8 -*-
"""In-class Univariate Analyses.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjfM4js4oKyo-kC54BavT3yHnpzQh6so
"""

import pandas as pd

df_nba = pd.read_csv("//Users/markkeith/Library/CloudStorage/GoogleDrive-mark.keith@gmail.com/My Drive/Colab Notebooks/data/nba_salaries.csv")

df_nba.head()

df_network = pd.read_csv("/Users/markkeith/Library/CloudStorage/GoogleDrive-mark.keith@gmail.com/My Drive/Colab Notebooks/data/network_traffic.csv")

df_network.head()

def univariate(df):
  import pandas as pd
  import numpy as np
  import matplotlib.pyplot as plt
  import seaborn as sns

  df_results = pd.DataFrame(columns=['Data Type', 'Count', 'Missing', 'Unique', 'Mode', 'Min', 'Q1', 'Median',
                                     'Q3', 'Max', 'Mean', 'Std Dev', 'Skewness', 'Kurtosis'])

  for col in df.columns:
    df_results.loc[col, 'Data Type'] = df[col].dtype
    df_results.loc[col, 'Count'] = df[col].count()
    df_results.loc[col, 'Missing'] = df[col].isnull().sum()
    df_results.loc[col, 'Unique'] = df[col].nunique()

    # Handle mode - might be empty if all values are unique
    mode_values = df[col].mode()
    if len(mode_values) > 0:
      df_results.loc[col, 'Mode'] = mode_values[0]
    else:
      df_results.loc[col, 'Mode'] = ""

    if df[col].dtype == 'int64' or df[col].dtype == 'float64':
      df_results.loc[col, 'Min'] = df[col].min()
      df_results.loc[col, 'Q1'] = df[col].quantile(0.25)
      df_results.loc[col, 'Median'] = df[col].median()
      df_results.loc[col, 'Q3'] = df[col].quantile(0.75)
      df_results.loc[col, 'Max'] = df[col].max()
      df_results.loc[col, 'Mean'] = df[col].mean()
      df_results.loc[col, 'Std Dev'] = df[col].std()
      df_results.loc[col, 'Skewness'] = df[col].skew()
      df_results.loc[col, 'Kurtosis'] = df[col].kurt()

  # Fill NaN values without triggering downcasting warning
  for col in df_results.columns:
    df_results[col] = df_results[col].astype(object)
    df_results.loc[df_results[col].isna(), col] = ""

  # Create visualizations
  for col in df.columns:
    # Determine if column is numeric or categorical
    is_numeric = df[col].dtype == 'int64' or df[col].dtype == 'float64'

    if is_numeric:
      # Numeric feature: stacked plot with box plot on top and histogram with KDE on bottom
      fig, (ax_box, ax_hist) = plt.subplots(2, 1, figsize=(10, 8),
                                             gridspec_kw={'height_ratios': [1, 2], 'hspace': 0.3})

      sns.set_style('ticks')

      flierprops = dict(marker='o', markersize=4, markerfacecolor='none', linestyle='none', markeredgecolor='gray')
      sns.boxplot(df[col], ax=ax_box, fliersize=4, saturation=0.50, width=0.50, linewidth=0.5, flierprops=flierprops)
      sns.histplot(data=df, x=col, ax=ax_hist, kde=True, color="orange")

      ax_box.set(yticks=[])
      ax_box.set(xticks=[])
      ax_box.set_xlabel('')
      sns.despine(ax=ax_hist)
      sns.despine(ax=ax_box, left=True, bottom=True)

      plt.suptitle(f'Univariate Analysis: {col}', fontsize=14, fontweight='bold', y=0.995)
      plt.tight_layout()
      plt.show()

    else:
      # Categorical feature: count plot with top 5 and bottom 5
      value_counts = df[col].value_counts()
      total_count = len(df[col].dropna())

      # Get top 5 and bottom 5
      top_5 = value_counts.head(5)
      bottom_5 = value_counts.tail(5)

      # Combine: top 5 (descending) + bottom 5 (ascending), avoiding duplicates
      combined_list = list(top_5.index) + list(reversed(bottom_5.index))
      combined_list = list(dict.fromkeys(combined_list))  # Remove duplicates while preserving order

      # Filter dataframe to only include these values
      plot_data = df[col][df[col].isin(combined_list)]

      # Create count plot
      plt.figure(figsize=(12, 6))
      ax = sns.countplot(y=plot_data, order=combined_list, orient='h')

      # Add percentage labels above bars
      plot_counts = plot_data.value_counts()
      max_count = plot_counts.max()
      for i, category in enumerate(combined_list):
        count = plot_counts[category]
        pct = (count / total_count) * 100
        # Position text to the right of the bar
        ax.text(count + max_count * 0.02, i, f'{pct:.1f}%',
                va='center', fontweight='bold', fontsize=10)

      plt.title(f'{col} - Top 5 and Bottom 5 Categories by Count', fontsize=12, fontweight='bold')
      plt.xlabel('Count', fontsize=11)
      plt.ylabel(col, fontsize=11)
      plt.grid(True, alpha=0.3, axis='x')
      plt.tight_layout()
      plt.show()

  return df_results

df_results = univariate(df_nba)
df_results

